[constant]
XLSX_SAVE_PATH = "xlsx_result"
VIDEO_SAVE_FOLDER_PATH = "video_out"
SAVE_FOLDER_PATH = "results"
SAMPLES_DIRECTORY = "data_for_denoise"
N2V_MODEL_NAME = "n2v_64x64_05_256_5"
N2V_MODEL_DIR = "models"
SAMPLE_NAME = "Mov_S4"
SAMPLE_EXTENSION = "avi"

SCALE_FACTOR = 2
MEAN_DATA_SAMPLE_RATE = 30

BILATERAL_D = 23
BILATERAL_SIGMA_COLOR = 75
BILATERAL_SIGMA_SPACE = 75

GAUSSIAN_K = 3
MEDIAN_K = 21

USE_ADAPTIVE = false
BINARY_THRESHOLD_MIN = 122
BINARY_THRESHOLD_MAX = 150

USE_NLM = true
NLM_H = 4
NLM_TEMPLATE_WINDOW_SIZE = 7
NLM_SEARCH_WINDOW_SIZE = 15

MORPH_OPERATIONS = [
    'open_7_1',
]

CONTOUR_EPSILON = 0.0001
CONTOUR_MIN_LENGTH = 5
CONTOUR_MIN_AREA = 380
CONTOUR_MIN_SOLIDITY = 0.12

OUT_VIDEO_FPS = "29.97"