[constant]
XLSX_SAVE_PATH = "xlsx_result"
VIDEO_SAVE_FOLDER_PATH = "video_out"
SAVE_FOLDER_PATH = "results"
SAMPLES_DIRECTORY = "data_for_denoise"
N2V_MODEL_NAME = "n2v_64x64_05_256_5"
N2V_MODEL_DIR = "models"
SAMPLE_NAME = "Mov_S6"
SAMPLE_EXTENSION = "mov"

SCALE_FACTOR = 2
MEAN_DATA_SAMPLE_RATE = 30

BILATERAL_D = 11
BILATERAL_SIGMA_COLOR = 35
BILATERAL_SIGMA_SPACE = 35

GAUSSIAN_K = 3
MEDIAN_K = 5

USE_ADAPTIVE = true
BINARY_THRESHOLD_MIN = 122
BINARY_THRESHOLD_MAX = 150

USE_NLM = true
NLM_H = 3
NLM_TEMPLATE_WINDOW_SIZE = 37
NLM_SEARCH_WINDOW_SIZE = 15

MORPH_OPERATIONS = [
    "open_5_1",
]

CONTOUR_EPSILON = 0.0001
CONTOUR_MIN_LENGTH = 5
CONTOUR_MIN_AREA = 380
CONTOUR_MIN_SOLIDITY = 0.12

OUT_VIDEO_FPS = "29.97"