TRAIN_IMAGES_DIRECTORY = 'images_for_train'
MODEL_DIRECTORY = 'models'
MODEL_NAME = 'n2v_64x64_05_256_5'

UNET_KERN_SIZE = 3
TRAIN_EPOCHS = 10
TRAIN_LOSS = 'mse'
BATCH_NORM = true
TRAIN_BATCH_SIZE = 64
N2V_PERC_PIX = 0.15
N2V_PATCH_SHAPE = 128
N2V_MANIPULATOR = 'uniform_withCP'
N2V_NEIGHBORHOOD_RADIUS = 91